CREATE 
VIEW VW_APURACAO_FATURAMENTO_DETALHADO AS
    SELECT 
        PR.COD_PRODUTO 		AS COD_PRODUTO,
        PR.NME_PRODUTO 		AS NME_PRODUTO,
        SUM(ITOP.QTD_ITEM) 	AS QTD_ITEM,
        AVG(ITOP.VLR_ITEM) 	AS VLR_PRECO_MEDIO,
        OP.DTA_OPERACAO 	AS DSC_PERIODO,
        OP.TPO_OPERACAO 	AS TPO_OPERACAO,
        PR.QTD_ESTOQUE_MIN 	AS QTD_ESTOQUE_MIN,
        PR.QTD_ESTOQUE_MAX 	AS QTD_ESTOQUE_MAX
    FROM
        ((OPERACAO OP
        JOIN ITEM_OPERACAO ITOP 	ON ((OP.COD_OPERACAO = ITOP.COD_OPERACAO)))
        JOIN PRODUTO PR 			ON ((PR.COD_PRODUTO = ITOP.COD_PRODUTO)))
    GROUP BY PR.COD_PRODUTO , PR.NME_PRODUTO , OP.DTA_OPERACAO , OP.TPO_OPERACAO