CREATE 
VIEW VW_APURACAO_FATURAMENTO_SUMARIZADO AS
    SELECT 
        A.COD_PRODUTO 															AS COD_PRODUTO,
        (B.QTD_ITEM * A.VLR_PRECO_MEDIO) 										AS VLR_CUSTO_VENDA,
        (B.QTD_ITEM * B.VLR_PRECO_MEDIO) 										AS VLR_FATURADO,
        ((B.QTD_ITEM * B.VLR_PRECO_MEDIO) - (B.QTD_ITEM * B.VLR_PRECO_MEDIO)) 	AS VLR_LIQUIDO,
        A.QTD_ITEM 																AS QTD_ITEM_ESTOQUE_ENTRADA,
        B.QTD_ITEM																AS QTD_ITEM_ESTOQUE_SAIDA,
        ROUND(((B.QTD_ITEM / a.QTD_ITEM) * 100),2) 								AS VLR_PCT_ESTOQUE_UTILIZADO,
        B.DSC_PERIODO 															AS DSC_PERIODO
    FROM
        ((SELECT 
            VAFD.QTD_ITEM 														AS QTD_ITEM,
			VAFD.VLR_PRECO_MEDIO 												AS VLR_PRECO_MEDIO,
			VAFD.COD_PRODUTO 													AS COD_PRODUTO,
			CAST(VAFD.DSC_PERIODO AS DATE) 										AS DSC_PERIODO
        FROM
            VW_APURACAO_FATURAMENTO_DETALHADO VAFD
        WHERE
            (VAFD.TPO_OPERACAO = 'C')) A
        JOIN (SELECT 
            VAFD.QTD_ITEM 														AS QTD_ITEM,
			VAFD.VLR_PRECO_MEDIO 												AS VLR_PRECO_MEDIO,
			VAFD.COD_PRODUTO 													AS COD_PRODUTO,
			CAST(VAFD.DSC_PERIODO AS DATE) 										AS DSC_PERIODO,
			VAFD.QTD_ESTOQUE_MIN 												AS QTD_ESTOQUE_MIN,
			VAFD.QTD_ESTOQUE_MAX 												AS QTD_ESTOQUE_MAX
        FROM
            VW_APURACAO_FATURAMENTO_DETALHADO VAFD
        WHERE
            (VAFD.TPO_OPERACAO = 'V')) b ON ((A.COD_PRODUTO = B.COD_PRODUTO)))