CREATE 
VIEW VW_FATURAMENTO_DETALHADO_ANUAL AS
    SELECT 
          VAPD.COD_PRODUTO 							
        , VAPD.NME_PRODUTO 							
        , SUM(VAPD.QTD_ITEM) 					AS QTD_ITEM
        , SUM(VAPD.VLR_PRECO_MEDIO) 			AS VLR_PRECO_MEDIO
        , DATE_FORMAT(VAPD.DTA_OPERACAO, '%Y') 	AS ANO_OPERACAO
    FROM
        VW_APURACAO_FATURAMENTO_DETALHADO VAPD
    WHERE
        VAPD.TPO_OPERACAO = 'V'
    GROUP BY 
		VAPD.COD_PRODUTO, 
		VAPD.NME_PRODUTO, 
		DATE_FORMAT(VAPD.DTA_OPERACAO, '%Y')