CREATE TABLE  DB_COMERCIO.ENDERECO (
  COD_ENDERECO 			INT				NOT NULL,
  DSC_COMPLEMENTO 		VARCHAR(255) 	NULL,
  NRO_ENDERECO 			INT 			NULL,
  DSC_PONTO_REFERENCIA 	VARCHAR(255) 	NULL,
  COD_CEP 				INT 			NULL,
  COD_PESSOA 			INT 			NULL,
  PRIMARY KEY (COD_ENDERECO),
  INDEX FK_ENDERECO_LOGRADOURO_IDX (COD_CEP ASC),
  INDEX FK_ENDERECO_PESSOA_IDX (COD_PESSOA ASC),
  CONSTRAINT FK_ENDERECO_LOGRADOURO
    FOREIGN KEY (COD_CEP)
    REFERENCES DB_COMERCIO.LOGRADOURO (COD_CEP),
  CONSTRAINT FK_ENDERECO_PESSOA
    FOREIGN KEY (COD_PESSOA)
    REFERENCES DB_COMERCIO.PESSOA (COD_PESSOA)
;
