CREATE TABLE IMAGEM_PRODUTO
	(
		COD_PRODUTO 	INT, 
        COD_IMAGEM 		INT, 
        PRIMARY KEY (COD_PRODUTO, COD_IMAGEM), 
        CONSTRAINT FK_IMAGEM_PRODUTO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
        CONSTRAINT FK_IMAGEM_PRODUTO_IMAGEM FOREIGN KEY (COD_IMAGEM) REFERENCES IMAGEM(COD_IMAGEM)
    );