CREATE TABLE  DB_COMERCIO.ITEM_OPERACAO (
  COD_ITEM_OPERACAO 	INT 			NOT NULL AUTO_INCREMENT,
  QTD_ITEM 				FLOAT 			NULL ,
  VLR_ITEM 				DECIMAL	(10,2) 	NULL ,
  COD_OPERACAO 			INT 			NOT NULL,
  COD_PRODUTO 			INT 			NOT NULL,
  PRIMARY KEY (COD_ITEM_OPERACAO),
  INDEX FK_ITEM_COMPRA_IDX (COD_OPERACAO ASC) ,
  INDEX FK_ITEM_COMPRA_PRODUTO_IDX (COD_PRODUTO ASC) ,
  CONSTRAINT FK_ITEM_COMPRA
    FOREIGN KEY (COD_OPERACAO)
    REFERENCES DB_COMERCIO.OPERACAO (COD_OPERACAO),
  CONSTRAINT FK_ITEM_COMPRA_PRODUTO
    FOREIGN KEY (COD_PRODUTO)
    REFERENCES DB_COMERCIO.PRODUTO (COD_PRODUTO)
)
;
