CREATE TABLE  DB_COMERCIO.LOGRADOURO (
  COD_CEP 			INT 			NOT NULL AUTO_INCREMENT,
  COD_BAIRRO 		INT 			NOT NULL,
  DSC_LOGRADOURO 	VARCHAR(255) 	NULL,
  DSC_COMPLEMENTO 	VARCHAR(255) 	NULL,
  PRIMARY KEY (COD_CEP, COD_BAIRRO),
  INDEX FK_BAIRRO_ENDERECO_IDX (COD_BAIRRO ASC) ,
  CONSTRAINT FK_BAIRRO_ENDERECO
    FOREIGN KEY (COD_BAIRRO)
    REFERENCES DB_COMERCIO.BAIRRO (COD_BAIRRO))
;