CREATE TABLE  DB_COMERCIO.BAIRRO (
  COD_BAIRRO 		INT 			NOT NULL AUTO_INCREMENT,
  NME_BAIRRO 		VARCHAR(100) 	NOT NULL,
  COD_MUNICIPIO 	INT 			NULL ,
  PRIMARY KEY (COD_BAIRRO),
  INDEX FK_BAIRRO_MUNICIPIO_IDX (COD_MUNICIPIO ASC) ,
  INDEX IDX_BAIRRO (NME_BAIRRO ASC) ,
  CONSTRAINT FK_BAIRRO_MUNICIPIO
    FOREIGN KEY (COD_MUNICIPIO)
    REFERENCES DB_COMERCIO.MUNICIPIO (COD_MUNICIPIO))
;
