CREATE TABLE  DB_COMERCIO.OPERACAO (
  COD_OPERACAO 		INT 			NOT NULL AUTO_INCREMENT,
  DTA_OPERACAO 		DATETIME 		NULL,
  COD_NOTA_FISCAL 	INT 			NULL,
  VRL_TOTAL 		DECIMAL(10,2) 	NULL,
  QTD_PARCELA 		INT 			NULL,
  TPO_STATUS ENUM('P', 'O') 		NULL 
	COMMENT 'P - PEDIDO (COMPRA OU VENDA); O - ORÇAMENTO\\N',
  COD_PESSOA 		INT 			NULL,
  FLG_PAGO 			TINYINT 		NULL,
  TPO_OPERACAO 		ENUM('C', 'V') 	NULL 
	COMMENT 'C - COMPRA; V - VENDA',
  PRIMARY KEY (COD_OPERACAO),
  INDEX FK_OPERACAO_PESSOA_IDX (COD_PESSOA ASC) VISIBLE,
  CONSTRAINT FK_OPERACAO_PESSOA
    FOREIGN KEY (COD_PESSOA)
    REFERENCES DB_COMERCIO.PESSOA (COD_PESSOA))
;