CREATE TABLE  DB_COMERCIO.PESSOA_FISICA (
  COD_PESSOA 			INT 			NOT NULL AUTO_INCREMENT,
  NME_PESSOA 			VARCHAR(100)	NULL,
  SGL_UF_NATURALIDADE 	CHAR(2)			NULL,
  DTA_NASCIMENTO 		DATE 			NOT NULL,
  TPO_SEXO ENUM('M', 'F', 'N') 
	COMMENT 'M - MASCULINO; F - FEMININO; N - NEUTRO',
  COD_USUARIO 			INT 			NULL,
  PRIMARY KEY (COD_PESSOA),
  INDEX FK_PESSOA_FISICA_PESSOA_IDX (COD_PESSOA ASC) ,
  CONSTRAINT FK_PESSOA_FISICA_USUARIO
    FOREIGN KEY (COD_USUARIO)
    REFERENCES DB_COMERCIO.USUARIO (COD_USUARIO)
);
