CREATE TABLE  DB_COMERCIO.PESSOA_JURIDICA (
  COD_PESSOA 		INT 			NOT NULL AUTO_INCREMENT,
  NME_RAZAO_SOCIAL 	VARCHAR(200) 	NOT NULL,
  NME_FANTASIA 		VARCHAR(200) 	NOT NULL,
  COD_USUARIO 		INT 			NOT NULL,
  PRIMARY KEY (COD_PESSOA),
  INDEX FK_PESSOA_JURIDICA_PESSOA_IDX (COD_PESSOA ASC) ,
  CONSTRAINT FK_PESSOA_JURIDICA_USUARIO
    FOREIGN KEY (COD_USUARIO)
    REFERENCES DB_COMERCIO.USUARIO (COD_USUARIO)
);