CREATE TABLE  DB_COMERCIO.PRODUTO (
	COD_PRODUTO 		INT 			NOT NULL AUTO_INCREMENT,
	NME_PRODUTO 		VARCHAR(95) 	NULL ,
	DSC_PRODUTO 		VARCHAR(255) 	NULL ,
	COD_SUBCATEGORIA 	INT 			NULL ,
	COD_UNIDADE_MEDIDA 	INT 			NULL ,
	QTD_ESTOQUE_MIN 	INT 			NULL ,
	QTD_ESTOQUE_MAX 	INT 			NULL ,
    COD_STATUS_ESTOQUE  INT GENERATED ALWAYS AS 
			(	CASE 	WHEN A.QTD_ESTOQUE_ATUAL BETWEEN A.QTD_ESTOQUE_MIN AND A.QTD_ESTOQUE_MAX THEN 1
					WHEN A.QTD_ESTOQUE_ATUAL < A.QTD_ESTOQUE_MIN THEN 2 
					WHEN A.QTD_ESTOQUE_ATUAL > A.QTD_ESTOQUE_MAX THEN 3
				END )VIRTUAL, /*COLUNA DERIVADA NÃO SUPORTADA PELO MYSQL 5.6*/
	DSC_STATUS_ESTOQUE VARCHAR(30) GENERATED ALWAYS AS 
			(	CASE 	WHEN A.QTD_ESTOQUE_ATUAL BETWEEN A.QTD_ESTOQUE_MIN AND A.QTD_ESTOQUE_MAX THEN 'ESTOQUE OK'
					WHEN A.QTD_ESTOQUE_ATUAL < A.QTD_ESTOQUE_MIN THEN 'ABAIXO DO MÍNIMO' 
					WHEN A.QTD_ESTOQUE_ATUAL > A.QTD_ESTOQUE_MAX THEN 'ACIMA DO MÁXIMO' 
				END )VIRTUAL,
  PRIMARY KEY (COD_PRODUTO),
  INDEX FK_PRODUTO_SUBCATEGORIA_IDX (COD_SUBCATEGORIA ASC) ,
  INDEX FK_PRODUTO_UNIDADE_MEDIDA_IDX (COD_UNIDADE_MEDIDA ASC) ,
  CONSTRAINT FK_PRODUTO_SUBCATEGORIA
    FOREIGN KEY (COD_SUBCATEGORIA)
    REFERENCES DB_COMERCIO.SUBCATEGORIA (COD_SUBCATEGORIA),
  CONSTRAINT FK_PRODUTO_UNIDADE_MEDIDA
    FOREIGN KEY (COD_UNIDADE_MEDIDA)
    REFERENCES DB_COMERCIO.UNIDADE_MEDIDA (COD_UNIDADE_MEDIDA))
;
