CREATE TABLE  DB_COMERCIO.UNIDADE_MEDIDA (
  COD_UNIDADE_MEDIDA 	INT 			NOT NULL AUTO_INCREMENT,
  NME_UNIDADE_MEDIDA 	VARCHAR(100) 	NULL ,
  SGL_UNIDADE_MEDIDA 	VARCHAR(50) 	NULL,
  PRIMARY KEY (COD_UNIDADE_MEDIDA))
;
