CREATE TABLE  DB_COMERCIO.USUARIO 
(
  COD_PESSOA 	INT 			NOT NULL AUTO_INCREMENT,
  DSC_LOGIN 	VARCHAR(20) 	NULL,
  DSC_SENHA 	VARCHAR(128) 	NULL,
  FLG_ATIVO 	TINYINT 		NULL,
  PRIMARY KEY (COD_PESSOA)
);